#!/bin/bash

# Configure main config files to reference these ones

[[ ! -f ~/.bash_aliases ]] && echo 'source ~/.conf/bashrc' > ~/.bash_aliases
[[ ! -f ~/.tmux.conf ]] && echo 'source-file ~/.conf/tmux.conf' > ~/.tmux.conf
[[ ! -f ~/.screenrc ]] && echo 'source ~/.conf/screenrc' > ~/.screenrc
[[ ! -f ~/.inputrc ]] && echo '$include ~/.conf/inputrc' > ~/.inputrc
[[ ! -f ~/.vimrc ]] && echo 'source ~/.conf/vimrc' > ~/.vimrc
