#!/bin/bash

# Configure main config files to reference these ones
declare -A configs
configs['.bash_aliases']='source ~/.conf/bashrc'
configs['.tmux.conf']='source-file ~/.conf/tmux.conf'
configs['.screenrc']='source ~/.conf/screenrc'
configs['.inputrc']='$include ~/.conf/inputrc'
configs['.vimrc']='source ~/.conf/vimrc'

# Insert the includes on line 1 of the file
for file in "${!configs[@]}"; do
    val=${configs["$file"]}
    if ! $(grep -q "$val" ~/$file); then
        sed -i "1i $val" ~/$file
    fi
done

# Copy over files that support neither environment nor inclusion
cp nanorc ~/.nanorc
