#!/bin/bash

# Configure main config files to reference these ones
declare -A configs
configs['.bash_aliases']='source ~/.conf/bashrc'
configs['.tmux.conf']='source-file ~/.conf/tmux.conf'
configs['.screenrc']='source ~/.conf/screenrc'
configs['.inputrc']='$include ~/.conf/inputrc'
configs['.vimrc']='source ~/.conf/vimrc'
configs['.hgrc']='%include ~/.conf/hgrc'

# Insert the includes on line 1 of the file
for file in "${!configs[@]}"; do
    val=${configs["$file"]}
    if ! [[ -e ~/$file ]]; then
        echo "echo $val > ~/$file"
        echo $val > ~/$file
    elif ! grep -q "$val" ~/$file; then
        echo "sed -i "1i $val" ~/$file"
        sed -i "1i $val" ~/$file
    fi
done

# Interactively copy over files lacking inclusion
diff -u ~/.nanorc ~/.conf/nanorc || cp -i ~/.conf/nanorc ~/.nanorc

